/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class juliacomm_TriangulacionJulia */

#ifndef _Included_juliacomm_TriangulacionJulia
#define _Included_juliacomm_TriangulacionJulia
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     juliacomm_TriangulacionJulia
 * Method:    triangular
 * Signature: ([D[D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_juliacomm_TriangulacionJulia_triangular
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
