/*
 * Copyright (C) 2014 Prometheus
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package triangulacion;

/**
 *
 */
public class TestFrame extends javax.swing.JFrame {

    public TestFrame(final TriangulacionOctave triangulacion) {
        initComponents();
        this.rtPanel.initialize(triangulacion);
    }

    public RealTimePanel getRT() {
        return this.rtPanel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtPanel = new triangulacion.RealTimePanel();
        jLabel1 = new javax.swing.JLabel();
        checkCams = new javax.swing.JCheckBox();
        checkSensors = new javax.swing.JCheckBox();
        checkBestCams = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Real Time Trianguleishon");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        rtPanel.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout rtPanelLayout = new javax.swing.GroupLayout(rtPanel);
        rtPanel.setLayout(rtPanelLayout);
        rtPanelLayout.setHorizontalGroup(
            rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        rtPanelLayout.setVerticalGroup(
            rtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jLabel1.setText("Capas:");

        checkCams.setText("Mostrar ángulos de visión");
        checkCams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCamsActionPerformed(evt);
            }
        });

        checkSensors.setText("Mostrar valores de sensores");
        checkSensors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSensorsActionPerformed(evt);
            }
        });

        checkBestCams.setText("Resaltar cámara escogida");
        checkBestCams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBestCamsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("by PROMETHEUS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(checkCams)
                    .addComponent(checkSensors)
                    .addComponent(checkBestCams)
                    .addComponent(jLabel2))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkCams)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkSensors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBestCams)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.rtPanel.close();
    }//GEN-LAST:event_formWindowClosing

    private void checkCamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCamsActionPerformed
        this.rtPanel.setShowCams(this.checkCams.isSelected());
    }//GEN-LAST:event_checkCamsActionPerformed

    private void checkSensorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSensorsActionPerformed
        this.rtPanel.setShowSensors(this.checkSensors.isSelected());
    }//GEN-LAST:event_checkSensorsActionPerformed

    private void checkBestCamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBestCamsActionPerformed
        this.rtPanel.setShowBestCam(this.checkBestCams.isSelected());
    }//GEN-LAST:event_checkBestCamsActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBestCams;
    private javax.swing.JCheckBox checkCams;
    private javax.swing.JCheckBox checkSensors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private triangulacion.RealTimePanel rtPanel;
    // End of variables declaration//GEN-END:variables
}
