#!/bin/sh

### BEGIN INIT INFO
# Provides:          locaviewer_sensors
# Required-Start:    $local_fs $network $remote_fs $syslog $time
# Required-Stop:     $local_fs $network $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Locaviewer - Sensores
# Description:       Recibe datos de los Bluetooth y lo publica.
### END INIT INFO

# Daemon paths
DIR=/home/pi/locaviewer/Comunicador
DAEMON="env LANG=es_ES.UTF-8 RTI_CONNEXT_PATH=/home/pi/RTI IS_RASPBERRY_PI=true PATH=/home/pi/apps/jdk1.8.0/bin:$PATH ./run_sensor.sh"
DAEMON_NAME=locaviewer_sensors

# Daemon options
DAEMON_ARGS=""

# User to run it.
DAEMON_USER=pi

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --quiet --chdir $DIR --user $DAEMON_USER --chuid $DAEMON_USER --make-pidfile --pidfile $PIDFILE --background --startas /bin/bash -- -c "exec $DAEMON $DAEMON_ARGS >> /home/pi/locaviewer.log 2>&1"
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0

