#!/bin/sh

### BEGIN INIT INFO
# Provides:          locaviewer_blue
# Required-Start:    $local_fs $network $remote_fs $syslog $time
# Required-Stop:     $local_fs $network $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Locaviewer - Bluetooth
# Description:       Inicia la obtención de datos de los sensores.
### END INIT INFO

# Daemon paths
DIR=/home/pi/locaviewer/Localizacion/Obtencion/
DAEMON="./sensor.py"
DAEMON_NAME=locaviewer_bluetooth

# Daemon options
DAEMON_ARGS="4554"

# User to run it.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --quiet --chdir $DIR --user $DAEMON_USER --chuid $DAEMON_USER --make-pidfile --pidfile $PIDFILE --background --startas /bin/bash -- -c "exec $DAEMON $DAEMON_ARGS >> /home/pi/locaviewer.log 2>&1"
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0

